from __future__ import annotations

import shutil
from pathlib import Path

from ..adapters import get_adapter
from ..adapters.base import PlatformAdapter, RenderContext

from .assets import assets_root, diff_trees, write_text
from .manifest import CANONICAL_SKILL_ROOT, validate_manifest


GENERATED_NOTICE = (
    "Generated by llm-wiki. Do not edit this file or platform mirrors by hand; "
    "edit `.agents/skills/` for skills and the agent-kit templates for instruction files."
)


def render_template(template_name: str, variables: dict[str, str]) -> str:
    template_path = assets_root() / "templates" / template_name
    if not template_path.is_file():
        raise FileNotFoundError(f"instruction template not found: {template_name}")
    text = template_path.read_text(encoding="utf-8")
    for key, value in variables.items():
        text = text.replace("{{ " + key + " }}", value)
        text = text.replace("{{" + key + "}}", value)
    return text.rstrip() + "\n"


def core_contract_text() -> str:
    path = assets_root() / "templates" / "core-contract.md.j2"
    if path.is_file():
        return path.read_text(encoding="utf-8").rstrip()
    raise FileNotFoundError("core-contract.md.j2")


def render_context() -> RenderContext:
    return RenderContext(core_contract=core_contract_text(), generated_notice=GENERATED_NOTICE)


def expected_instruction(adapter: PlatformAdapter) -> str:
    context = render_context()
    return render_template(adapter.template_name, adapter.render_vars(context))


def expected_generated_files(adapter: PlatformAdapter) -> dict[Path, str]:
    return adapter.generated_config_files(render_context())


def mirror_drift(root: Path, adapter: PlatformAdapter) -> list[str]:
    source = root / CANONICAL_SKILL_ROOT
    target = root / adapter.skill_root
    diffs = diff_trees(source, target)
    return [
        f"{adapter.skill_root.as_posix()}/missing:{item}" for item in diffs.missing
    ] + [
        f"{adapter.skill_root.as_posix()}/changed:{item}" for item in diffs.changed
    ] + [
        f"{adapter.skill_root.as_posix()}/extra:{item}" for item in diffs.extra
    ] + adapter.mirror_state_drift(root)


def check_one_platform(root: Path, platform: str) -> list[str]:
    adapter = get_adapter(platform)
    issues: list[str] = []
    instruction_path = root / adapter.instruction_file
    expected = expected_instruction(adapter)
    if not instruction_path.exists():
        issues.append(adapter.instruction_file.as_posix())
    elif instruction_path.read_text(encoding="utf-8").rstrip() != expected.rstrip():
        issues.append(adapter.instruction_file.as_posix())
    for rel_path, expected_text in expected_generated_files(adapter).items():
        path = root / rel_path
        if not path.exists():
            issues.append(rel_path.as_posix())
        elif path.read_text(encoding="utf-8").rstrip() != expected_text.rstrip():
            issues.append(rel_path.as_posix())
    source_skills = root / CANONICAL_SKILL_ROOT
    if not source_skills.is_dir():
        issues.append(CANONICAL_SKILL_ROOT.as_posix())
    elif adapter.mirror_skills:
        issues.extend(mirror_drift(root, adapter))
    return issues


def sync_one_platform(root: Path, platform: str, actions: list[str], check: bool) -> list[str]:
    adapter = get_adapter(platform)
    if check:
        return check_one_platform(root, platform)

    instruction_path = root / adapter.instruction_file
    write_text(instruction_path, expected_instruction(adapter), actions, dry_run=False)
    for rel_path, expected_text in expected_generated_files(adapter).items():
        write_text(root / rel_path, expected_text, actions, dry_run=False)
    if adapter.mirror_skills:
        source = root / CANONICAL_SKILL_ROOT
        target = root / adapter.skill_root
        if not source.is_dir():
            raise FileNotFoundError(f"canonical skills not found: {source}")
        if target.exists():
            shutil.rmtree(target)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, target, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        adapter.write_mirror_state(root)
        actions.append(f"sync {source} -> {target}")
    if platform == "codex":
        plans_dir = root / ".codex" / "plans"
        plans_dir.mkdir(parents=True, exist_ok=True)
        actions.append(f"mkdir {plans_dir}")
    return []


def sync_platforms(root: Path, *, platforms: list[str], check: bool) -> int:
    kb_root = root.resolve()
    actions: list[str] = []
    any_drift = False
    metadata_issues = validate_manifest(kb_root, platforms)
    if check and metadata_issues:
        any_drift = True
        print("[drift] metadata")
        for issue in metadata_issues:
            print(f"  - {issue}")
    for platform in platforms:
        drifts = sync_one_platform(kb_root, platform, actions, check=check)
        if check:
            if drifts:
                any_drift = True
                print(f"[drift] {platform}")
                for item in drifts:
                    print(f"  - {item}")
            else:
                print(f"[ok] {platform}")
    if check:
        return 1 if any_drift else 0

    print(f"[synced] {kb_root}")
    for action in actions:
        print(f"- {action}")
    return 0
